### ISSUE TITLE
Populate Stats on Homepage

### ISSUE THREAD

**Issue by tedpedersen** [tedpedersen/group-project-uc-berkeley#2]
On load, the entire US stats should load. If the user searches for a state, that state should load. If user clicks show my location button use the geolocation API to show the stats for the state they are in. The arrow icon should display up or down from the previous day.

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

It would be cool to have a typeahead like this, would also help prevent bad requests: https://twitter.github.io/typeahead.js/examples/

**Comment by tedpedersen** [comment]
https://api.covid19api.com/total/dayone/country/united-states

**Comment by tedpedersen** [comment]
Got the typeahead working, so you don't have to do validation, user will always pass a valid state as a value:

<img width="658" alt="Screen Shot 2020-06-30 at 7 25 55 PM" src="https://user-images.githubusercontent.com/929079/86196267-bee40080-bb07-11ea-8cb9-2cbc8ac67930.png">

**Comment by vanessalane** [comment]
Surfaced the global stats instead of the US stats. For simplicity, I'm going to break this issue into surfacing the stats and create a new one to take the user's input.
