### ISSUE TITLE
Add preloader to map

### ISSUE THREAD

**Issue by tedpedersen** [tedpedersen/group-project-uc-berkeley#22]
While map is loading data show the preloader and hide the map:

<img width="420" alt="Screen Shot 2020-07-03 at 12 47 21 PM" src="https://user-images.githubusercontent.com/929079/86494767-5c6b4a00-bd2b-11ea-8062-524e775e03a2.png">

When the map is done loading data, hide the preloader and display the map.

you can use jQuery inside of your existing function:
$("#pac-card").hide();
$("#loader").show();

$("#loader").hide();
$("#pac-card").show();

**Comment by vcaruso0923** [comment]
Done! Had to take it in a different route, but the functionality is there.
