### ISSUE TITLE
Save users searches in local storage

### ISSUE THREAD

**Issue by tedpedersen** [tedpedersen/group-project-uc-berkeley#3]
If SAVED SEARCHES button is clicked, show a list of states the user has searched for in the modal. If nothing, state that. if populated, user can click on a searched state, modal closes, and the map and stats populate. User can also delete their local storage: localStorage.removeItem(key);

**Comment by tedpedersen** [comment]
On load, perhaps check local storage and populate with last search.

**Comment by vcaruso0923** [comment]
Done!
