### ISSUE TITLE
Figure out long-term solution for geocoding

### ISSUE THREAD

**Issue by tedpedersen** [tedpedersen/group-project-uc-berkeley#30]
We need to find another solution for geocoding, as google is too expensive for the amount of calls we make, limiting it to only use our domain didn't help, and I won't be able to afford to keep the app live after the grading.

**Comment by vcaruso0923** [comment]
One option would be to geocode all the locations one time, get the latitudes.longitudes that the geocoding returns, and store them locally in a JSON file. Then, when the function runs, fetch the lats/longs from the stored file as opposed to geocoding them again.

**Comment by vcaruso0923** [comment]
//Get data one time from current logic:
Line 197 in map.js:
console.log('{"' + locationName + '" : "' + latLng + '"},')
//copy all the data from that console log into a new .js file geocodes.js
//this is the format we are going for:
geocodeData = '[{"locationName" : "latLng"},{"locationName" : "latLng"},{"locationName" : "latLng"}]';
module.exports = geocodeData;

//map.js
//Put this line at the top of the file:
const geocodeData = require("./geocode.js");

//replace line 196 with:
var latLang = geocodeData[0].locationName
//remove lines 180-195

**Comment by vanessalane** [comment]
We can also replace the geocoding feature with a typeahead like you originally had? I used the geolocation api because I needed country code and it seemed like an easy way to set up autocomplete for smaller regions, but we could always generate the potential locations based on the countries/states/counties in the API response.

**Comment by vcaruso0923** [comment]
Stored Latitudes/Longitudes for testing locations on places.js so no more geocoding is needed
